### ISSUE TITLE
Details about sentence embedding model trained on human translated data called "sentence_embedding_transformer_hd""

### ISSUE THREAD

**Issue by MohammedRakib** [Foysal87/sbnltk#2]
@Foysal87 May I know exactly which transformer model have you used? Is it a custom model or a traditional model like bert. Is the model available on HuggingFace Models Hub? Also  is the human translated data publicly available?

**Comment by Foysal87** [comment]
I have a repository regarding sentence embedding. I used google translated data. But now, we have some human-evaluated data in the Bangla language. so you can also train by that data.
